title: 'Ubeyde Emir Özdemir'
description: 'Personal website and portfolio of Ubeyde Emir Özdemir, a Software Engineering graduate and JavaScript developer.'
keywords: 'ubeyde, emir, özdemir, ubeyde emir, ubeyde özdemir, ubeyde emir özdemir'
url: 'https://ubeyde.me'
baseurl: ''
lang: 'en'
timezone: 'Europe/Istanbul'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
      show_banner: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - vendor
